Repository exercism/pyret, pull requests merged in 2023-12, with the labels that each got.

#171 Fix argument order for list-ops
  exercises/practice/list-ops/list-ops.arr
Labels: x:action/proofread, x:rep/tiny, x:action/fix

#172 Simplify queen-attack stub
  exercises/practice/queen-attack/queen-attack.arr
Labels: x:rep/tiny

#173 Simplify simple-linked-list stub
  exercises/practice/simple-linked-list/simple-linked-list.arr
Labels: x:rep/tiny

#174 Configlet sync docs and metadata
  exercises/practice/acronym/.docs/instructions.md
  exercises/practice/armstrong-numbers/.docs/instructions.md
  exercises/practice/bank-account/.meta/config.json
  exercises/practice/binary-search/.docs/instructions.md
  exercises/practice/clock/.meta/config.json
  exercises/practice/hello-world/.meta/config.json
  exercises/practice/isogram/.docs/instructions.md
  exercises/practice/list-ops/.docs/instructions.md
  exercises/practice/perfect-numbers/.docs/instructions.md
  exercises/practice/phone-number/.docs/instructions.md
  exercises/practice/pop-count/.meta/config.json
  exercises/practice/protein-translation/.docs/instructions.md
  exercises/practice/queen-attack/.docs/instructions.md
  exercises/practice/series/.docs/instructions.md
  exercises/practice/strain/.meta/config.json
Labels: x:rep/tiny

#175 Update anagram tests
  exercises/practice/anagram/.meta/tests.toml
  exercises/practice/anagram/anagram-test.arr
Labels: x:action/sync, x:rep/tiny

#169 Dnd character
  exercises/practice/dnd-character/.meta/example.arr
  exercises/practice/dnd-character/.meta/tests.toml
  exercises/practice/dnd-character/dnd-character.arr
Labels: x:rep/small, x:module/practice-exercise, x:action/sync, x:action/fix
