Repository exercism/pyret, pull requests merged in 2023-11, with the labels that each got.

#51 Add flatten-array
  config.json
  exercises/practice/flatten-array/.docs/instructions-append.md
  exercises/practice/flatten-array/.docs/instructions.md
  exercises/practice/flatten-array/.meta/config.json
  exercises/practice/flatten-array/.meta/example.arr
  exercises/practice/flatten-array/.meta/tests.toml
  exercises/practice/flatten-array/flatten-array-test.arr
  exercises/practice/flatten-array/flatten-array.arr
Labels: x:module/practice-exercise, x:rep/large, x:type/content, x:knowledge/none

#19 Initial implementation of the clock exercise
  config.json
  exercises/practice/clock/.docs/instructions-append.md
  exercises/practice/clock/.docs/instructions.md
  exercises/practice/clock/.meta/config.json
  exercises/practice/clock/.meta/example.arr
  exercises/practice/clock/.meta/tests.toml
  exercises/practice/clock/clock-test.arr
  exercises/practice/clock/clock.arr
Labels: x:module/practice-exercise, x:rep/medium, x:type/content

#161 pop-count: update metadata
  config.json
  exercises/practice/pop-count/.meta/config.json
Labels: x:size/tiny

#164 CI: pin GitHub Actions runners
  .github/workflows/test.yml
Labels: x:size/tiny

#165 CI: pin GitHub Actions workflows
  .github/workflows/test.yml
Labels: x:size/tiny
