Repository exercism/pyret, pull requests merged in 2024-02, with the labels that each got.

#184 `pop-count`: rename to `eliuds-eggs`
  config.json
  exercises/practice/eliuds-eggs/.docs/instructions.md
  exercises/practice/eliuds-eggs/.docs/introduction.md
  exercises/practice/eliuds-eggs/.meta/config.json
  exercises/practice/eliuds-eggs/.meta/example.arr
  exercises/practice/eliuds-eggs/.meta/tests.toml
  exercises/practice/eliuds-eggs/pop-count-test.arr
  exercises/practice/eliuds-eggs/pop-count.arr
Labels: x:size/tiny

#185 Fix remaining pop-count references
  exercises/practice/eliuds-eggs/.meta/config.json
  exercises/practice/eliuds-eggs/eliuds-eggs-test.arr
  exercises/practice/eliuds-eggs/eliuds-eggs.arr
Labels: x:rep/tiny

#186 Deprecate binary search
  config.json
Labels: x:rep/tiny

#188 Update track docs
  docs/INSTALLATION.md
  docs/LEARNING.md
  docs/RESOURCES.md
  docs/TESTS.md
  exercises/shared/.docs/debug.md
  exercises/shared/.docs/help.md
  exercises/shared/.docs/tests.md
Labels: x:rep/tiny, x:type/docs

#189 Update INSTALLATION.md
  docs/INSTALLATION.md
Labels: x:rep/tiny, x:type/docs

#190 Forego parallel-letter-frequency
  config.json
Labels: x:rep/tiny

#191 Typo in list-ops test name
  exercises/practice/list-ops/list-ops-test.arr
Labels: x:rep/tiny
