Repository exercism/pyret, pull requests merged in 2024-03, with the labels that each got.

#193 Fix function names in test example
  README.md
Labels: x:action/proofread, x:rep/tiny

#195 Sync docs and metadata
  exercises/practice/raindrops/.docs/instructions.md
  exercises/practice/raindrops/.docs/introduction.md
  exercises/practice/raindrops/.meta/config.json
  exercises/practice/reverse-string/.docs/instructions.md
  exercises/practice/reverse-string/.docs/introduction.md
  exercises/practice/reverse-string/.meta/config.json
  exercises/practice/roman-numerals/.docs/instructions.md
  exercises/practice/roman-numerals/.docs/introduction.md
  exercises/practice/roman-numerals/.meta/config.json
  exercises/practice/strain/.meta/config.json
Labels: x:action/sync, x:rep/tiny, x:action/create

#196 Add circular buffer
  config.json
  exercises/practice/circular-buffer/.docs/instructions.md
  exercises/practice/circular-buffer/.meta/config.json
  exercises/practice/circular-buffer/.meta/example.arr
  exercises/practice/circular-buffer/.meta/tests.toml
  exercises/practice/circular-buffer/circular-buffer-test.arr
  exercises/practice/circular-buffer/circular-buffer.arr
Labels: x:module/practice-exercise, x:action/sync

#176 Add robot-simulator
  config.json
  exercises/practice/robot-simulator/.docs/instructions.md
  exercises/practice/robot-simulator/.meta/config.json
  exercises/practice/robot-simulator/.meta/example.arr
  exercises/practice/robot-simulator/.meta/tests.toml
  exercises/practice/robot-simulator/robot-simulator-test.arr
  exercises/practice/robot-simulator/robot-simulator.arr
Labels: x:module/practice-exercise, x:rep/medium

#199 Standardize difficulty and sort exercises
  config.json
Labels: x:rep/tiny

#202 Fix allergies UUID
  config.json
Labels: x:rep/tiny

#204 Sync with problem-specs
  exercises/practice/anagram/.meta/tests.toml
  exercises/practice/darts/.docs/instructions.md
  exercises/practice/darts/.meta/config.json
  exercises/practice/flatten-array/.docs/instructions.md
  exercises/practice/reverse-string/.meta/tests.toml
  exercises/practice/two-fer/.docs/instructions.md
  exercises/practice/two-fer/.docs/introduction.md
Labels: x:rep/small, x:action/sync

#205 add sieve exercise
  config.json
  exercises/practice/sieve/.docs/instructions.md
  exercises/practice/sieve/.docs/introduction.md
  exercises/practice/sieve/.meta/config.json
  exercises/practice/sieve/.meta/example.arr
  exercises/practice/sieve/.meta/tests.toml
  exercises/practice/sieve/sieve-test.arr
  exercises/practice/sieve/sieve.arr
Labels: x:module/practice-exercise, x:rep/medium
